# Generated by Django 5.1 on 2024-08-25 15:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.parkingspot')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type_de_véhicule', models.CharField(default='voiture', max_length=20)),
                ('numéro_de_plaque', models.CharField(default='0000 abc', max_length=20)),
                ('date_d_arriver', models.DateField(default=django.utils.timezone.now)),
                ('date_de_départ', models.DateField(default=django.utils.timezone.now)),
                ('heure_d_arriver', models.DateTimeField(default=datetime.datetime(2024, 8, 25, 8, 0, 59, 918084, tzinfo=datetime.timezone.utc))),
                ('heure_de_départ', models.DateTimeField(default=datetime.datetime(2024, 8, 25, 9, 0, 59, 918084, tzinfo=datetime.timezone.utc))),
                ('parking_place', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.parkingplace')),
                ('parking_spot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.parkingspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
