# Generated by Django 5.1 on 2024-08-26 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='heure_d_arriver',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 8, 0, 2, 323610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='heure_de_départ',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 9, 0, 2, 323610, tzinfo=datetime.timezone.utc)),
        ),
    ]
